# Generated by Django 5.1.7 on 2025-03-11 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grupo', models.CharField(choices=[('1AI', '1_A_infantil'), ('1BI', '1_B_infantil'), ('1CI', '1_C_infantil'), ('1DI', '1_D_infantil'), ('1EI', '1_E_infantil'), ('2AI', '2_A_infantil'), ('2BI', '2_B_infantil'), ('2CI', '2_C_infantil'), ('2DI', '2_D_infantil'), ('3AI', '3_A_infantil'), ('3BI', '3_B_infantil'), ('3CI', '3_C_infantil'), ('3DI', '3_D_infantil'), ('1AP', '1_A_primaria'), ('1BP', '1_B_primaria'), ('1CP', '1_C_primaria'), ('1DP', '1_D_primaria'), ('2AP', '2_A_primaria'), ('2BP', '2_B_primaria'), ('2CP', '2_C_primaria'), ('3AP', '3_A_primaria'), ('3BP', '3_B_primaria'), ('3CP', '3_C_primaria'), ('4AP', '4_A_primaria'), ('4BP', '4_B_primaria'), ('5AP', '5_A_primaria'), ('5BP', '5_B_primaria'), ('6AP', '6_A_primaria'), ('6BP', '6_B_primaria')], max_length=3)),
                ('Nombre', models.CharField(max_length=200)),
                ('Sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('NA', 'Sin especificar')], max_length=2)),
                ('Observaciones', models.TextField(blank=True, max_length=300, null=True)),
                ('PET_KET', models.CharField(blank=True, choices=[('PET', 'PET'), ('KET', 'KET')], default='', max_length=3)),
                ('Telefono_contacto_padre', models.PositiveIntegerField(blank=True, null=True)),
                ('Nombre_padre', models.CharField(blank=True, max_length=30, null=True)),
                ('Email_padre', models.EmailField(blank=True, max_length=254, null=True)),
                ('Telefono_contacto_madre', models.PositiveIntegerField(blank=True, null=True)),
                ('Nombre_madre', models.CharField(blank=True, max_length=30, null=True)),
                ('Email_madre', models.EmailField(blank=True, max_length=254, null=True)),
                ('Personas_autorizadas_recogida', models.TextField(blank=True, max_length=300, null=True)),
                ('Comedor', models.BooleanField(default=False)),
                ('Alergias', models.TextField(blank=True, max_length=300, null=True)),
                ('IBAN', models.CharField(blank=True, max_length=24, null=True)),
                ('Titular_cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('Beca_comedor', models.BooleanField(default=False)),
                ('Pagos_pendientes', models.TextField(blank=True, max_length=300, null=True)),
                ('Adhesion_Accede', models.BooleanField(default=False)),
                ('Senal_Accede', models.BooleanField(default=False)),
                ('Tutor_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Nombre'],
            },
        ),
    ]
