# Generated by Django 5.1.7 on 2025-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumn',
            name='Pagos_pendientes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
