# Generated by Django 5.1.7 on 2025-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alumn_pagos_pendientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumn',
            options={'ordering': ['Grupo', 'Nombre']},
        ),
        migrations.AlterField(
            model_name='alumn',
            name='Adhesion_Accede',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='alumn',
            name='Beca_comedor',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='alumn',
            name='Comedor',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='alumn',
            name='PET_KET',
            field=models.CharField(blank=True, choices=[('PET', 'PET'), ('KET', 'KET'), ('None', 'None')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='alumn',
            name='Senal_Accede',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
    ]
