# Generated by Django 5.1.7 on 2025-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alumn_options_alter_alumn_adhesion_accede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumn',
            name='Fotografia',
            field=models.URLField(blank=True, null=True),
        ),
    ]
