# Generated by Django 5.1.7 on 2025-03-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alumn_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumn',
            name='Calificaciones',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
